/// Flutter icons MesIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MesIcon
///      fonts:
///       - asset: fonts/MesIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MesIcon {
  MesIcon._();

  static const _kFontFam = 'MesIcon';
  static const String? _kFontPkg = null;

  static const IconData castle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData international_menu = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localisation_card = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
